# Generated by Django 4.1.7 on 2023-03-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categorias_remove_livro_categoria_livro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='descricao',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
