# Generated by Django 4.1.7 on 2023-03-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_livro_descricao_alter_categorias_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='anunciado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
