# Generated by Django 4.1.7 on 2023-03-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_livro_anunciado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='anunciado',
        ),
        migrations.AddField(
            model_name='livro',
            name='emprestar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livro',
            name='preco_emprestimo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='livro',
            name='preco_venda',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='livro',
            name='trocar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='vender',
            field=models.BooleanField(default=False),
        ),
    ]
