# Generated by Django 4.1.7 on 2023-03-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_livro_anunciado_livro_emprestar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
    ]
