# Generated by Django 4.1.7 on 2023-03-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_livro_emprestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Honório Fraga', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='compras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='livros_emprestados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='livros_pegados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='trocas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='vendas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livro',
            name='trocar',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(default='1M02', max_length=50)),
                ('escola', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.escola')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='escola',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.escola'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='serie',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.serie'),
        ),
    ]
